### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by birdmanmandbir** [lonelyprince7/Cloze_Test#1]
It is successful for 1 GPU trainning. But if I use Multi GPU trainning, there is nan loss after some steps, which make the trainning unsuccessful.
Do you have any advice? Or have you experienced that?

**Comment by orion-orion** [comment]
Emmm,I also used four GTX1080Ti to train and everthing go well,Perhaps the problem is resulted from pytorch?

**Comment by birdmanmandbir** [comment]
Could you tell me the version of your pytorch? 
This is my run.sh:
```
CUDA_DEVICES=0,1,2,3
python3 -u main.py \
--data_dir \
./data/ \
--bert_model \
./bert-models/bert-base-uncased.tar.gz \
--do_eval --do_train --train_batch_size 4 \
--output_dir ./trained_model \
--learning_rate 1e-5 --num_train_epochs 4
```
This is the log:
```
device cuda n_gpu 8 distributed training False
loading ./data/train-bert-base-uncased.pt
02/12/2020 20:04:12 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file ./bert-
models/bert-base-uncased.tar.gz to temp dir /tmp/tmpoqzmdt0w
02/12/2020 20:04:15 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

02/12/2020 20:04:17 - INFO - pytorch_pretrained_bert.modeling -   Weights from pretrained model n
ot used in BertForCloth: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
***** Running training *****
  Batch size = 4
  Num steps = 5550/home/undergrats/anaconda3/envs/asc_pre2020/lib/python3.7/site-packages/torch/nn/parallel/_functi
ons.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars
; will instead unsqueeze and return a vector.  warnings.warn('Was asked to gather along dimension 0, but all '
..................
step: 500 | train loss: 0.012677162885665894 | train acc 0.8013544082641602
step: 510 | train loss: 0.014172337017953396 | train acc 0.8491124510765076
step: 520 | train loss: 0.009785844944417477 | train acc 0.7798319458961487
step: 530 | train loss: 0.00966687686741352 | train acc 0.7579710483551025
step: 540 | train loss: 0.011226761154830456 | train acc 0.7337461113929749
step: 550 | train loss: 0.00999370589852333 | train acc 0.7615262269973755
step: 560 | train loss: nan | train acc 0.2930232584476471
step: 570 | train loss: nan | train acc 0.24668434262275696
```

And there is also one weird thing:
I set 4 gpu in `run.sh`, and there are actually 4 gpu enabled in training, but the log shows n_gpu is 8

**Comment by orion-orion** [comment]
I use the pytorch1.2 and I dont make sure whether the  "CUDA_DEVICES" equals to the "CUDA_VISIBLE_DEVICES",may be you can modify it to "CUDA_VISIBLE_DEVICES"  and  have  a try?

**Comment by birdmanmandbir** [comment]
Yes I have tried it but the log is the same, and my pytorch is 1.4, maybe I should use 1.2?
Do you have following warning in your log?
```
UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
```

**Comment by foxbrucecui** [comment]
root@61deee9487e7ca709a9c7602:~/Cloze_Test# python3 -u main.py --data_dir ./data/ --bert_model albert-xxlarge-v2  --do_eval --do_train --train_batch_size 4 --output_dir ./trained_model --learning_rate 1e-5 --num_train_epochs 4
device cuda n_gpu 1 distributed training False
loading ./data/train-albert-xxlarge-v2.pt
***** Running training *****
  Batch size = 4
  Num steps = 4693
Traceback (most recent call last):
  File "main.py", line 348, in <module>
    main()
  File "main.py", line 235, in main
    for inp, tgt in train_data.data_iter():
  File "/root/Cloze_Test/data_util.py", line 207, in data_iter
    inp, tgt, file_name = self._batchify(cache_data, data_batch)
  File "/root/Cloze_Test/data_util.py", line 186, in _batchify
    file_name.append(data.file_name)
AttributeError: 'ClothSample' object has no attribute 'file_name'
请问这是什么问题

**Comment by orion-orion** [comment]
> root@61deee9487e7ca709a9c7602:~/Cloze_Test# python3 -u main.py --data_dir ./data/ --bert_model albert-xxlarge-v2 --do_eval --do_train --train_batch_size 4 --output_dir ./trained_model --learning_rate 1e-5 --num_train_epochs 4 device cuda n_gpu 1 distributed training False loading ./data/train-albert-xxlarge-v2.pt ***** Running training ***** Batch size = 4 Num steps = 4693 Traceback (most recent call last): File "main.py", line 348, in main() File "main.py", line 235, in main for inp, tgt in train_data.data_iter(): File "/root/Cloze_Test/data_util.py", line 207, in data_iter inp, tgt, file_name = self._batchify(cache_data, data_batch) File "/root/Cloze_Test/data_util.py", line 186, in _batchify file_name.append(data.file_name) AttributeError: 'ClothSample' object has no attribute 'file_name' 请问这是什么问题

I am sorry for responding to your issue so late(I am busy with my undergraduation project recently). On my computer, it works well:

![image](https://user-images.githubusercontent.com/46917784/152638993-184248dc-e395-4ae7-82ac-c234e977eefb.png)
So I think perhaps the bug is caused by the version of the pytorch or python(My pytorch version is 1.8.0 and python version is 3.9).
